name: NISA Monitor

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

# ↓↓↓ この2行を追加することで、書き込み権限（Write）を直接許可できます ↓↓↓
permissions:
  contents: write

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: コードを読み込み
        uses: actions/checkout@v4

      - name: Pythonの準備
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: ライブラリのインストール
        run: |
          pip install -r requirements.txt

      - name: プログラム実行
        run: python monitor.py
